-- Create the categories table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  name_pt TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Categories are viewable by everyone" ON public.categories
  FOR SELECT USING (true);

-- Create policy to allow authenticated users (admin) to insert/update/delete
CREATE POLICY "Categories are editable by authenticated users" ON public.categories
  FOR ALL USING (auth.role() = 'authenticated');

-- Insert the default categories based on the current hardcoded list
INSERT INTO public.categories (slug, name_en, name_ar, name_pt, order_index)
VALUES
  ('vip-sets', 'VIP Sets', 'أطقم VIP', 'Conjuntos VIP', 1),
  ('cork-eco', 'Cork & Eco', 'فِلّين وبيئة', 'Cortiça & Eco', 2),
  ('notebooks-premium', 'Premium Notebooks', 'دفاتر فاخرة', 'Cadernos Premium', 3),
  ('notebooks-usb', 'USB Notebooks', 'دفاتر فلاش', 'Cadernos USB', 4),
  ('tech-gifts', 'Tech & Electronics', 'تقنية وإلكترونيات', 'Tecnologia', 5),
  ('business-gifts', 'Business Gifts', 'هدايا أعمال', 'Brindes Executivos', 6),
  ('corporate-sets', 'Corporate Sets', 'أطقم الشركات', 'Conjuntos Corporativos', 7),
  ('promotional', 'Promotional', 'دعائي', 'Promocional', 8),
  ('pens-writing', 'Pens & Writing', 'أقلام وكتابة', 'Canetas', 9),
  ('accessories', 'Accessories', 'إكسسوارات', 'Acessórios', 10),
  ('seasonal', 'Seasonal', 'موسمي', 'Sazonal', 11),
  ('general', 'General', 'عام', 'Geral', 12)
ON CONFLICT (slug) DO NOTHING;
