-- 1. Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('product', 'set')),
  catalogue TEXT,
  category TEXT,
  category_name TEXT,
  names JSONB,
  image TEXT,
  featured BOOLEAN DEFAULT false,
  tags TEXT[],
  includes TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Quote Requests Table
CREATE TABLE quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  customer_company TEXT,
  items JSONB,
  message TEXT,
  locale TEXT,
  status TEXT DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Setup Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_requests ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Permissions)
-- Allow anyone to read products
CREATE POLICY "Products are viewable by everyone." ON products FOR SELECT USING (true);
-- Allow anyone to add products (temporarily, for our migration script)
CREATE POLICY "Products can be inserted by anyone." ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Products can be updated by anyone." ON products FOR UPDATE USING (true);

-- Allow anyone to submit a quote request (but they can't read others' requests)
CREATE POLICY "Anyone can insert quote requests." ON quote_requests FOR INSERT WITH CHECK (true);
